<?php
return array(
	'author-social-links' =>array(
		'behance'       => 'Behance',
		'delicious'     => 'Delicious',
		'deviantart'    => 'Deviantart',
		'facebook'      => 'Facebook',
		'flickr'        => 'Flickr',
		'foursquare'    => 'Foursquare',
		'lastfm'        => 'Lastfm',
		'linkedin'      => 'Linkedin',
		'git'           => 'Github',
		'google-plus'   => 'Google+',
		'instagram'     => 'Instagram',
		'odnoklassniki' => 'Odnoklassniki',
		'pinterest'     => 'Pinterest',
		'rss'           => 'RSS',
		'skype'         => 'Skype',
		'soundcloud'    => 'Soundcloud',
		'stumbleupon'   => 'Stumbleupon',
		'tripAdvisor'   => 'TripAdvisor',
		'tumblr'        => 'Tumblr',
		'twitter'       => 'Twitter',
		'vimeo'         => 'Vimeo',
		'vk'            => 'VK',
		'weibo'         => 'Weibo',
		'xing'          => 'XING',
		'youtube'       => 'YouTube',
	),
	'header-social' => array(
		'facebook'   => 'fa-facebook',
		'twitter'    => 'fa-twitter',
		'google-plus'=> 'fa-google-plus',
		'pinterest'  => 'fa-pinterest',
		'instagram'  => 'fa-instagram',
		'dribbble'   => 'fa-dribbble',
		'facebook'   => 'fa-facebook',
	),
	'social-icons' =>array(
		'facebook'      => 'fa-facebook-square',
		'twitter'       => 'fa-twitter',
		'google'        => 'fa-google-plus-square',
		'skype'         => 'fa-skype',
		'youtube'       => 'fa-youtube-square',
		'rss'           => 'fa-rss',
		'delicious'     => 'fa-delicious',
		'flickr'        => 'fa-flickr',
		'lastfm'        => 'fa-lastfm',
		'linkedin'      => 'fa-linkedin',
		'vimeo'         => 'fa-vimeo',
		'tumblr'        => 'fa-tumblr',
		'pinterest'     => 'fa-pinterest',
		'deviantart'    => 'fa-deviantart',
		'git'           => 'fa-git',
		'instagram'     => 'fa-instagram',
		'soundcloud'    => 'fa-soundcloud',
		'stumbleupon'   => 'fa-stumbleupon',
		'behance'       => 'fa-behance',
		'tripAdvisor'   => 'fa-tripadvisor',
		'vk'            => 'fa-vk',
		'foursquare'    => 'fa-foursquare',
		'xing'          => 'fa-xing',
		'weibo'         => 'fa-weibo',
		'odnoklassniki' => 'fa-odnoklassniki',
	),
	'sort_blog' => array(
		esc_html__( '- Latest -', 'bignews' )               => '',
		esc_html__( 'A to Z', 'bignews' )                   => 'az_order',
		esc_html__( 'Z to A', 'bignews' )                   => 'za_order',
		esc_html__( 'Random posts today', 'bignews' )       => 'random_today',
		esc_html__( 'Random posts a week ago', 'bignews' )  => 'random_7_day',
		esc_html__( 'Random posts a month ago', 'bignews' ) => 'random_month',
		esc_html__( 'Random Posts', 'bignews' )             => 'random_posts',
		esc_html__( 'Most Commented', 'bignews' )           => 'comment_count',
		esc_html__( 'Popular', 'bignews' )                  => 'popular',
	),
	'style_formats' => array(
		'swbignews_dropcap' => array(
			'title' => 'Dropcaps',
			'items' => array(
				array(
					'parent_id' => 'swbignews_dropcap',
					'title' => 'Box',
					'classes' => 'dropcap',
					'inline' => 'span',
				),
				array(
					'parent_id' => 'swbignews_dropcap',
					'title' => 'Circle',
					'classes' => 'dropcap1',
					'inline' => 'span',
				),
				array(
					'parent_id' => 'swbignews_dropcap',
					'title' => 'Regular',
					'classes' => 'dropcap2',
					'inline' => 'span',
				),
				array(
					'parent_id' => 'swbignews_dropcap',
					'title' => 'Bold',
					'classes' => 'dropcap3',
					'inline' => 'span',
				),
			)
		),
		'swbignews_text_highlight' => array(
			'title' => 'Text highlighting',
			'items' => array(
				array(
					'parent_id' => 'swbignews_text_highlight',
					'title' => 'Black censured',
					'classes' => 'highlight',
					'inline' => 'span',
				),
				array(
					'parent_id' => 'swbignews_text_highlight',
					'title' => 'Red marker',
					'classes' => 'highlight_maker red',
					'inline' => 'span',
				),
				array(
					'parent_id' => 'swbignews_text_highlight',
					'title' => 'Blue marker',
					'classes' => 'highlight_maker blue',
					'inline' => 'span',
				),
				array(
					'parent_id' => 'swbignews_text_highlight',
					'title' => 'Green marker',
					'classes' => 'highlight_maker green',
					'inline' => 'span',
				),
				array(
					'parent_id' => 'swbignews_text_highlight',
					'title' => 'Yellow  marker',
					'classes' => 'highlight_maker yellow ',
					'inline' => 'span',
				),
				array(
					'parent_id' => 'swbignews_text_highlight',
					'title' => 'Pink  marker',
					'classes' => 'highlight_maker pink ',
					'inline' => 'span',
				),
			)
		),
		'swbignews_blockquote' => array(
			'title' => 'Text Blockquote',
			'items' => array(
				array(
					'parent_id' => 'swbignews_blockquote',
					'title'		=> 'Style 01',
					'block'		=> 'blockquote',
					'classes'	=> 'blockquote-01 blockquote',
					'wrapper'	=> true,
				),
				array(
					'parent_id' => 'swbignews_blockquote',
					'title' => 'Style 02',
					'block'		=> 'blockquote',
					'classes'	=> 'blockquote-02 blockquote',
					'wrapper'	=> true,
				),
				array(
					'parent_id' => 'swbignews_blockquote',
					'title' => 'Style 03',
					'block'		=> 'blockquote',
					'classes'	=> 'blockquote-03 blockquote',
					'wrapper'	=> true,
				),
				array(
					'parent_id' => 'swbignews_blockquote',
					'title' => 'Style 04',
					'block'		=> 'blockquote',
					'classes'	=> 'blockquote-04 blockquote',
					'wrapper'	=> true,
				),
			)
		)
	),
	'post-format-icons' => array(
		'standard' => '',
		'video'    => 'fa-video-camera',
		'gallery'  => 'fa-picture-o',
	),
	'social-counter' => array(
		'facebook'		=> 'fa-facebook',
		'youtube'		=> 'fa fa-youtube',
		'twitter'		=> 'fa-twitter',
		'google'		=> 'fa-google-plus',
		'vimeo'			=> 'fa fa-vimeo',
		'soundcloud'	=> 'fa fa-soundcloud',
		'instagram'		=> 'fa fa-instagram',
		'rss'			=> 'fa fa-rss'
	),
	'recent_post_style' => array(
		'1'      => 'Grid',
		'2'      => 'Feature Image', 
	),
	'advertisement' => array(
		'header'		=> 'Top banner',
		'sidebar'		=> 'Sidebar banner 01',
		'sidebar-02'	=> 'Sidebar banner 02',
		'content'		=> 'Content banner',
		'content02'		=> 'Content banner 02',
		'content03'		=> 'Content banner 03'
	),
	'widget-block' => array(
		'1,1'   => 'Block 1',
		'6,1'   => 'Block 6',
		'8,1'   => 'Block 8',
		'9,1'   => 'Block 9',
		'9,1,2' => 'Block 9 - Style 2',
		'10,1'   => 'Block 10',
	),
	'widget-carousel' => array(
		'1'   => 'Carousel 1',
		'2'   => 'Carousel 2',
		'4'   => 'Carousel 4',
	),
	'ads_options' => array(
		'ads_display'	=> 'shw-display-banner-%s',
		'ads_image'		=> 'shw-banner-%s',
		'ads_link'		=> 'shw-banner-%s-link',
		'ads_alt'		=> 'shw-banner-%s-alt',
		'ads_target'	=> 'shw-banner-%s-newtab',
		'ads_code'		=> 'shw-banner-%s-textarea',
		'ads_spacing'	=> 'shw-spacing-banner-%s'
	),
	'league_options' =>array( 
		'league-1' =>	esc_html__( 'Liga', 'bignews' ),
		'league-2' =>	esc_html__( 'Ligue 1', 'bignews' ),
		'league-3' =>	esc_html__( 'Serie A', 'bignews' ),
		'league-4' =>	esc_html__( 'Bundesliga', 'bignews' ),
		'league-5' =>	esc_html__( 'Eredivisie', 'bignews' ),
		'league-6' =>	esc_html__( 'Pro League', 'bignews' ),
		'league-7' =>	esc_html__( 'Premier League', 'bignews' ),
	),
);